### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Kabron287** [atomic14/m5stack-core2-audio-monitor#4]
Signal quality could be significally improved with the following minimal code modification:
1. In **main.cpp**  
**.sample_rate = 64000,**  // this expands frequency range to 8 kHz
2. In **I2SSampler.cpp**
////                    int16_t i2sData[1024];
                    **int16_t i2sData[2048];**                    
                    // read from i2s
////                    i2s_read(sampler->m_i2sPort, i2sData, 2048, &bytesRead, 10);
                    **i2s_read(sampler->m_i2sPort, i2sData, 4096, &bytesRead, 10);**                    
////                    for (int i = 0; i < bytesRead / 2; i++)
                    **for (int i = 0; i < bytesRead / 2; i+=2)**  

Photos show aquired signal before and after modification.
![before](https://user-images.githubusercontent.com/2493191/134773264-f7e02546-4faf-469b-905c-07ce5c143bc1.jpg)

![after](https://user-images.githubusercontent.com/2493191/134773270-d70c2b4b-db32-417a-9cd2-dc82fa5e119d.jpg)

**Comment by cgreening** [comment]
This is great - would you like to create a pull request and we can merge your changes in?

**Comment by Kabron287** [comment]
@cgreening 
Sorry, I'm not experienced enough in git. 
I tried to fork, clone, fetch, checkout, ets., but faulty. 
So, please do it yourself.

**Comment by cgreening** [comment]
Closed by 77d128476904fe6986e032d86c7cb30b94b589fc
