### ISSUE TITLE
cant clone repository

### ISSUE THREAD

**Issue by magnetus26** [atomic14/m5stack-core2-audio-monitor#6]
I get the following error when using :
git clone --recursive git@github.com:atomic14/m5stack-core2-audio-monitor.git

![image](https://user-images.githubusercontent.com/22038983/164121296-7dd2aa3a-2561-48d0-94a3-62e0f18db5ec.png)

and the following issue when cloning repo using Visual Studio Code:
https://github.com/atomic14/m5stack-core2-audio-monitor.git

![image](https://user-images.githubusercontent.com/22038983/164121513-b69975d1-f4a2-4b19-8891-2c4324a89eb5.png)

**Comment by sybrenstuvel** [comment]
The URL in the README is only suitable for people with write/commit access to the repository. Use this instead, it'll work.

```
git clone https://github.com/atomic14/m5stack-core2-audio-monitor.git
```

**Comment by sybrenstuvel** [comment]
I've updated the README in 2d29dcf5d2bad6e63dee65e70829b0c5cc5e3bde.
