### ISSUE TITLE
Open to formatting changes?

### ISSUE THREAD

**Issue by sybrenstuvel** [atomic14/m5stack-core2-audio-monitor#9]
Hello,

I've made a few changes to the code, and I wouldn't mind sending in a few pull requests. For one, I needed to remove DC offset from the samples before applying the Hamming window. I also have some smaller changes (which I feel are improvements), like reducing indentation level and removing an unnecessary cast.

However, for me to work on the code comfortably, I reformatted the code. In my day job I work on [Blender](https://projects.blender.org/blender/blender/), and it's just more comfortable for me to keep using their C++ code style in my personal projects too (so I don't need to switch). [My fork](https://github.com/sybrenstuvel/m5stack-core2-audio-monitor/tree/sybren) of this repo has all my changes.

The thing is, this project didn't include any formatting configuration, and so my changes to the formatting will make future PRs hard to merge. Would you be willing to copy my formatting changes? Or have any other `.clang-format` rules that ensure consistent formatting? That would make it significantly easier for me to contribute. It's fine if you say no -- it's only some minor changes, I'm not planning to make this my life's only purpose ;-)

Cheers,
Sybren

**Comment by cgreening** [comment]
Why don't I make a you a contributor to the project?

**Comment by sybrenstuvel** [comment]
Hah, that would simplify things, yeah :)

**Comment by sybrenstuvel** [comment]
Thanks for the access! I've pushed my changes to the `main` branch.
